c-subsidietrekker-nginx:
    build: .
    dockerfile: Dockerfile-nginx
    volumes:
        - ../app/static/:/usr/share/nginx/html/static/
    links:
        - c-subsidietrekker-app
    ports:
        - "80:80"
c-subsidietrekker-app:
    build: .
    volumes:
        - ../app/:/opt/subsidietrekker
    links:
        - c-subsidietrekker-elasticsearch
c-subsidietrekker-elasticsearch:
    image: elasticsearch:2.3.5
